# Generated by Django 5.2 on 2025-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafimage',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafimage',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
