# Generated by Django 5.2 on 2025-04-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_leafimage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leafimage',
            old_name='predicted_disease',
            new_name='predicted_label',
        ),
    ]
